### PR TITLE
Add role to install vim by default.

### PR DESCRIPTION
**Pull request by luizfar**

### CODE REVIEW

**Comment by bltavares** [comment]
Should we name the role `applications` so we can expand it in the future with other programs?

**Comment by luizfar** [comment]
Done.

**Comment by bltavares** [comment]
There is no alpine package on the default arch repo
https://www.archlinux.org/packages/?sort=&q=alpine&maintainer=&last_update=&flagged=&limit=50

We could use the aur repo to install alpine
There is an example of using aur to install packages [here](https://github.com/bltavares/tty.space/blob/master/roles/nntp.sh#L15-L16)

Another option is to provide `mutt` instead. Or both.

**Comment by luizfar** [comment]
:+1:

**Comment by bltavares** [comment]
Thank you for flying Vim.

**Pull request merged**
